### ISSUE TITLE
Incompatible with Table of Contents Plus Plugin

### ISSUE THREAD

**Issue by ChristianRies** [imagely/nextgen-gallery#11]
Hi, since weeks my website does not work with Nextgen Gallery 3.9.x series. I kept version 3.8 until this morning, but updated it to 3.9.3 by mistake and again my website did not work anymore (white screen). I reinstalled 3.8 but could not activate it anymore, it produced php errors. I then disabled my plugins one after the other and I found out that Nextgen Gallery (since version 3.9.0 until 3.9.3) is not working with Table of Contents Plus anymore.
Thanks for having a look into this. Kind regards, Christian

**Comment by bowens** [comment]
Thanks @ChristianRies !

I've installed Table of Contents Plus locally but I'm not able to reproduce any problems so far. One thing that could cause problems though: under their Main Options section there's a field "Auto insert for the following content types" that includes several of our custom post types. Please make sure none of the following are selected:

- ngg_pricelist
- ngg_pricelist_item
- ngg_order
- ngg_album
- ngg_gallery
- ngg_pictures
- lightbox_library
- photocrati-comments
- ngg_coupon
- nextgen_proof
- displayed_gallery
- display_type
- gal_display_source

If that doesn't solve the problem could you please share the PHP error? I may be able to diagnose the problem then.

**Comment by ChristianRies** [comment]
Thanks Benjamin,

I think you looked into it too late, so that the last update of NGG solved the problem. That might explain why you can't reproduce the error.

Kind regards

Christian

Dr. Christian Ries
Department of Ecology
National Museum of Natural History
25, rue Münster
L-2160 Luxembourg
Email: ***@***.******@***.***>
On 6/14/21 9:55 PM, Benjamin Owens wrote:

Thanks @ChristianRies<https://github.com/ChristianRies> !

I've installed Table of Contents Plus locally but I'm not able to reproduce any problems so far. One thing that could cause problems though: under their Main Options section there's a field "Auto insert for the following content types" that includes several of our custom post types. Please make sure none of the following are selected:

  *   ngg_pricelist
  *   ngg_pricelist_item
  *   ngg_order
  *   ngg_album
  *   ngg_gallery
  *   ngg_pictures
  *   lightbox_library
  *   photocrati-comments
  *   ngg_coupon
  *   nextgen_proof
  *   displayed_gallery
  *   display_type
  *   gal_display_source

If that doesn't solve the problem could you please share the PHP error? I may be able to diagnose the problem then.

**Comment by bowens** [comment]
Thanks @ChristianRies!
